import { Header, Footer } from '../components/Index'
import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import "./globals.css";
import { theme } from "../theme";
import "@mantine/core/styles.css";
// import '@mantine/dates/styles.css';
// import '@mantine/dropzone/styles.css';
import '@mantine/code-highlight/styles.css';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Header />
          {children}
          <Footer />
          <ToastContainer />
        </MantineProvider>
      </body>
    </html>
  );
}
